# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 2.6.4
          bundler-cache: true
      - name: Instalar depedências
        run:  |
              sudo su - 
              gem install bundler             
      - name: Instalar o Capybara
        run: gem install capybara
      - name: Abrir o Gemfile
        run: |
          echo "gem 'capybara', '~> 3.35', '>= 3.35.3'" >> Gemfile
          echo "gem 'cucumber', '~> 7.0'" >> Gemfile
          echo "gem 'faker'" >> Gemfile
          echo "gem 'ffaker'" >> Gemfile
          echo "gem 'ffi'" >> Gemfile
          echo "gem 'png_quantizator'" >> Gemfile
          echo "gem 'pry'" >> Gemfile
          echo "gem 'rubocop-airbnb'" >> Gemfile
          echo "gem 'rufo'" >> Gemfile
          echo "gem 'os', '1.1.0'" >> Gemfile
          echo "gem 'report_builder', '1.9'" >> Gemfile
          echo "gem 'rspec', '3.9.0'" >> Gemfile
          echo "gem 'selenium-webdriver', '3.142.7'" >> Gemfile
          echo "gem 'activesupport', '~> 5.0'" >> Gemfile
          bundler install
          cat Gemfile
      - name: Verifica se o Ruby está instalado
        run: ruby -v
      
                            

             
            
          

